name: bon_plant_local_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls

  intl: ^0.18.0
  flutter_svg: ^2.0.1
  simple_shadow: ^0.3.0
  flutter_slidable: ^2.0.0
  slidable_button: ^1.3.1
  flutter_fadein: ^2.0.0
  jiffy: ^5.0.0
  #syncfusion_flutter_pdfviewer: ^20.4.51
  hovering: ^1.0.4
  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0+2
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.8.2
  file_selector_linux: ^0.9.0+1
  image_picker_for_web: ^2.1.8
  url_launcher: ^6.1.5
  #flutter_neumorphic: ^3.2.0
  window_manager: ^0.2.7
  video_player_win: ^2.2.0
  video_player: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
